apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-horizontals
spec:
  generators:
  - git:
      repoURL: https://https://github.com/MTuradek/argocd-applicationset.git
      revision: HEAD
      directories:
      - path: apps/*
  template:
    metadata:
      name: horizontals
    spec:
      project: default
      source:
        repoURL: https://https://github.com/MTuradek/argocd-applicationset.git
        targetRevision: HEAD
        path: horizontals
      destination:
        server: https://kubernetes.default.svc
        namespace: horizontals
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true

